name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Or 'master', check your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # 1. Go to your project folder
            cd /var/www/ciputraColorRun
            
            # 2. Pull the latest changes (Use HTTPS url if SSH fails inside server)
            git pull origin main
            
            # 3. Install new dependencies
            npm install
            
            # 4. Build (Delete this line if not using Next.js/React)
            npm run build
            
            # 5. Restart the server so users see the new version
            pm2 restart all